name: benchmark
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12.11
  - catboost=1.2.8
  - igraph=0.11.9
  - imbalanced-learn=0.14.0
  - matplotlib=3.10.6
  - networkx=3.5
  - numpy=1.26.0
  - optuna=4.5.0
  - pandas=2.3.2
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pytorch-lightning=2.5.5
  - scanpy=1.11.4
  - scikit-learn=1.7.2
  - scipy=1.15.3
  - umap-learn=0.5.9.post2
  - wandb=0.22.0