name: benchmark
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12.11
  - absl-py=2.3.1
  - anndata=0.12.2
  - captum=0.8.0
  - catboost=1.2.8
  - category-encoders=2.8.1
  - colorama=0.4.6
  - colorlog=6.9.0
  - contourpy=1.3.1
  - crc32c=2.7.1
  - cuda-cudart=12.4.127
  - cuda-cudart_linux-64=13.0.88
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-runtime=12.4.1
  - dill=0.4.0
  - filelock=3.17.0
  - fsspec=2025.7.0
  - gitdb=4.0.12
  - gitpython=3.1.45
  - grpcio=1.76.0
  - h5py=3.14.0
  - igraph=0.11.9
  - imbalanced-learn=0.14.0
  - ipykernel=6.30.1
  - ipython=8.30.0
  - ipywidgets=8.1.5
  - jinja2=3.1.6
  - joblib=1.5.2
  - jupyter=1.1.1
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - lightning=2.5.5
  - lightning-utilities=0.15.2
  - llvmlite=0.45.0
  - matplotlib=3.10.6
  - ml-collections=1.1.0
  - morgoth=1.5
  - mudata=0.3.2
  - multiprocess=0.70.18
  - narwhals=2.5.0
  - natsort=8.4.0
  - networkx=3.5
  - notebook=7.0.8
  - numba=0.62.0
  - numcodecs=0.16.3
  - numexpr=2.11.0
  - numpy=1.26.0
  - nvidia-nccl-cu12=2.28.3
  - optuna=4.5.0
  - optuna-integration=4.5.0
  - pandas=2.3.2
  - pillow=11.3.0
  - plotly=6.3.0
  - polars=1.34.0
  - polars-runtime-32=1.34.0
  - protobuf=6.32.1
  - psutil=7.0.0
  - pyarrow=21.0.0
  - pydantic=2.11.9
  - pygments=2.19.1
  - pynndescent=0.5.13
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pytorch-lightning=2.5.5
  - pyyaml=6.0.2
  - requests=2.32.5
  - rich=14.2.0
  - ruff=0.12.0
  - scanpy=1.11.4
  - scikit-learn=1.7.2
  - scikit-misc=0.5.1
  - scipy=1.15.3
  - scvi-tools=1.4.0.post1
  - seaborn=0.13.2
  - sentry-sdk=2.39.0
  - setuptools=78.1.1
  - shapely=2.1.2
  - smmap=5.0.2
  - smogn=0.1.2
  - sparse=0.17.0
  - statsmodels=0.14.5
  - sympy=1.13.1
  - tensorboard=2.20.0
  - tensorboard-data-server=0.7.2
  - tensorboardx=2.6.4
  - threadpoolctl=3.5.0
  - torchmetrics=1.8.2
  - torchtriton=3.1.0
  - tqdm=4.67.1
  - umap-learn=0.5.9.post2
  - urllib3=2.1.0
  - wandb=0.22.0
  - xarray=2025.10.1
  - xgboost=3.0.5
  - zarr=3.1.3
  - zeromq=4.3.5
  - zipp=3.21.0